### ISSUE TITLE
stage0 gcc3 needs patching in order to build in gcc >=4.3

### ISSUE THREAD

**Issue by roytam1** [sabotage-linux/sabotage#28]
Otherwise error message will block building gcc3:
/usr/include/bits/fcntl2.h:51: error: call to '__open_missing_mode' declared with attribute error: open with O_CREAT in second argument needs 3 arguments

see also: https://bugs.launchpad.net/ubuntu/+source/hdf5/+bug/286565/comments/6
